# 1. Write a Python Program to Add Two Matrices?


In [1]:
import numpy as np

mat1 = np.array([[1,2,4],
        [4,5,6],
        [7,8,9]])
mat2 = np.array([[2,3,4],
        [5,6,7],
        [8,9,1]])

sumMat = np.add(mat1,mat2)
print("The Sum of two matrix \n\n{}  and \n\n{}  is \n\n{} ".format(mat1,mat2,sumMat))

The Sum of two matrix 

[[1 2 4]
 [4 5 6]
 [7 8 9]]  and 

[[2 3 4]
 [5 6 7]
 [8 9 1]]  is 

[[ 3  5  8]
 [ 9 11 13]
 [15 17 10]] 


# 2. Write a Python Program to Multiply Two Matrices?


In [2]:
import numpy as np

mat1 = np.array([[1,2,4],
        [4,5,6],
        [7,8,9]])
mat2 = np.array([[2,3,4],
        [5,6,7],
        [8,9,1]])

sumMat = np.dot(mat1,mat2)
print("The product of two matrix \n\n{}  and \n\n{}  is \n\n{} ".format(mat1,mat2,sumMat))

The product of two matrix 

[[1 2 4]
 [4 5 6]
 [7 8 9]]  and 

[[2 3 4]
 [5 6 7]
 [8 9 1]]  is 

[[ 44  51  22]
 [ 81  96  57]
 [126 150  93]] 


# 3. Write a Python Program to Transpose a Matrix?



In [4]:
def initializeMatrix(n,v=0):
    M=[]             
    for i in range(n):
        #stor row
        row =[]
        for j in range(n):
            row.append(v)
        M.append(row)
    return(M)

def createMatrix(n):
    
    M=[]             
    print("Enter the element :")
    for i in range(n):
        #stor row
        row =[]
        for j in range(n):
            row.append(int(input()))
        M.append(row)
    return(M)

def printMatrix(M,n):
    for i in range(n):
        for j in range(n):
            print(M[i][j], end=" ")
        print() 
        
def transposeMatrix(M,n,result):
    for i in range(n):
        for j in range(n):
            result[i][j]= M[j][i]
    return result

n=int(input("Enter N for N x N matrix: "))       
M1 = createMatrix(n)
#Display the 2D array
print("Display Array M1 In Matrix Form")
printMatrix(M1,n)

result = initializeMatrix(n)
result = transposeMatrix(M1,n,result)
print("Transposed Matrix")
for r in result:
    print(r)

Enter N for N x N matrix: 6
Enter the element :
6
7
8
9
7
6
5
4
5
3
3
2
5
3
6
7
4
1
1
1
4
5
3
9
6
7
6
9
3
3
1
6
3
7
2
7
Display Array M1 In Matrix Form
6 7 8 9 7 6 
5 4 5 3 3 2 
5 3 6 7 4 1 
1 1 4 5 3 9 
6 7 6 9 3 3 
1 6 3 7 2 7 
Transposed Matrix
[6, 5, 5, 1, 6, 1]
[7, 4, 3, 1, 7, 6]
[8, 5, 6, 4, 6, 3]
[9, 3, 7, 5, 9, 7]
[7, 3, 4, 3, 3, 2]
[6, 2, 1, 9, 3, 7]


# 4. Write a Python Program to Sort Words in Alphabetic Order?


In [7]:
str = input("Enter some string")

words = str.split()
words.sort()
for word in words:
    print(word) 

Enter some stringwe are about to win
about
are
to
we
win


# . Write a Python Program to Remove Punctuation From a String?


In [9]:
punctuations = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''

str = input("Enter some string with panctuations  ")

no_punct = ""
for char in str:
    if char not in punctuations:
        no_punct = no_punct + char

print(no_punct)

Enter some string with panctuations  hey there !!!!
hey there 
